name: Locale

on:
  push:
    paths:
      - packages/i18n/**
      - locales/**
      - .github/workflows/locale.yml
  pull_request:
    paths:
      - packages/i18n/**
      - locales/**
      - .github/workflows/locale.yml
jobs:
  locale_verify:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9
      - name: Setup libvips
        uses: ./.github/actions/setup-libvips
      - name: Setup mise
        uses: jdx/mise-action@v2
      - run: pnpm i --frozen-lockfile
      - run: pnpm --filter i18n build
      - name: Verify Locales
        working-directory: ./packages/i18n
        run: pnpm run verify
